# templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "{{ .Values.app.name }}={{ .Values.app.image.repository }}/{{ .Values.app.image.name }}"
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.update-strategy: newest-build
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.allow-tags: regexp:^numpy\.v\..*__pandas\.v\..*__mongodb__nginx$
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.force-update: "true"
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.registry-url: "http://{{ .Values.app.image.repository | split ':' | first }}"
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.insecure: "true"
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.allow-insecure-http: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization:/argo-cd
    argocd-image-updater.argoproj.io/{{ .Values.app.name }}.pull-secret: "pullsecret:argocd/{{ .Values.app.imagePullSecret }}"
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: HEAD
    path: argo-cd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
