apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-neutrino-ui
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "10.20.153.64:8082/repository/8bit-community/<DOCKER_IMAGE_NAME>"
    argocd-image-updater.argoproj.io/new-neutrino-ui.update-strategy: semver
    argocd-image-updater.argoproj.io/new-neutrino-ui.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/new-neutrino-ui.pull-secret: nexus-docker-registry
spec:
  project: default
  source:
    repoURL: https://github.com/singamrkreddy/argocd-project.git
    targetRevision: HEAD
    path: new-neutrino-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true