apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-neutrino-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-neutrino-ui
  template:
    metadata:
      labels:
        app: new-neutrino-ui
    spec:
      hostAliases:
      - ip: "198.18.20.39"
        hostnames:
        - "shopgw.ctrls.com"
      containers:
      - name: new-neutrino-ui
        image: "10.20.153.64:8082/repository/8bit-community/new-neutrino-ui  # No tag is mentioned latest tag will be used by Image Updater
        imagePullPolicy: Always
        ports:
        - containerPort: 22
      imagePullSecrets:
      - name: nexus-docker-registry
        
