# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "8bit-numpy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "8bit-numpy"
  template:
    metadata:
      labels:
        app: "8bit-numpy"
    spec:
      containers:
      - name: "8bit-numpy"
        image: "10.20.153.64:8082/8bit-official/8bit-numpy-1.21.0-ubuntu-20.04:numpy.v.1.21.0__pandas.v.1.3.0__mongodb__nginx"
        imagePullPolicy: Always
        ports:
        - containerPort: 22
      imagePullSecrets:
      - name: "nexus-docker-registry"
