apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: 10.20.153.64:8082/8bit-official/8bit-numpy-1.21.0-ubuntu-20.04
  newTag: "numpy.v.1.21.0__pandas.v.1.3.0__mongodb__nginx"
