# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "8bit-numpy-1.21.0-ubuntu-20.04"
spec:
  selector:
    app: "8bit-numpy-1.21.0-ubuntu-20.04"
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
