# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "{{app.name}}"
spec:
  selector:
    app: "{{app.name}}"
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: {{app.port}}
    targetPort: {{app.port}}
