# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "numpy-service"
spec:
  selector:
    app: "8bit-numpy"
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
