apiVersion: v1
kind: Service
metadata:
  name: "$app_name-service"
spec:
  type: NodePort
  selector:
    app: "$app_name"
  ports:
    - name: http 
      port: 80
      targetPort: 80
    - name: ssh
      port: 22
      targetPort: 22
    - name: jupyter
      port: 8888
      targetPort: 8888
