apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ubuntu20-04-python"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ubuntu20-04-python"
  template:
    metadata:
      labels:
        app: "ubuntu20-04-python"
    spec:
      containers:
        - name: "ubuntu20-04-python"
          image: "10.20.153.64:8082/repository/8bit-community/ubuntu20-04-python:python"
          ports:
            - name: http 
              containerPort: 80
      imagePullSecrets:
        - name: "nexus-docker-registry"
