apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{app-name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{app-name}}"
  template:
    metadata:
      labels:
        app: "{{app-name}}"
    spec:
      containers:
        - name: "{{app-name}}"
          image: "{{nexus-url}}/{{nexus-repo}}/{{app-name}}:{{tag}}"
          ports:
            - name: http 
              containerPort: 80
      imagePullSecrets:
        - name: "{{nexus-secret-name}}"
