apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name | quote }}
    spec:
      containers:
      - name: {{ .Values.app.name | quote }}
        image: "{{ .Values.app.image.repository }}/{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.port }}
      imagePullSecrets:
      - name: {{ .Values.app.imagePullSecret | quote }}
