# values.yaml
app:
  name: 8bit-numpy-1-21-0-ubuntu-20-04-test
  replicas: 1
  image:
    repository: "10.20.153.64:8082/repository/8bit-official"
    name: "8bit-numpy-1.21.0-ubuntu-20.04"
    tag: "tensorflow.v.2.10__numpy.v.1.21.0__xgboost.v.1.6.0__opencv.v.4.5.5__mongodb_nginx"
  port: 22
  imagePullSecret: "nexus-docker-registry"

service:
  name: test-8bit-numpy-service
  type: NodePort
  portName: ssh
  protocol: TCP

argocd:
  repoURL: "https://github.com/singamrkreddy/argocd-project.git"
  namespace: "default"
