# values.yaml
app:
  name: 8bit-numpy-1.21.0-ubuntu-20.04
  replicas: 1
  image:
    repository: "10.20.153.64:8082/8bit-official"
    name: "8bit-numpy-1.21.0-ubuntu-20.04"
    tag: "numpy.v.1.21.0__pandas.v.1.3.0__mongodb__nginx"
  port: 22
  imagePullSecret: "nexus-docker-registry"
